# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(),
        ),
    ]
